# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minio_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13minio_service.proto\x12\rminio_service\"P\n\x11\x46ileUploadRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\x12\x13\n\x0b\x62ucket_name\x18\x02 \x01(\t\x12\x13\n\x0bobject_name\x18\x03 \x01(\t\"6\n\x12\x46ileUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"U\n\x13UploadObjectRequest\x12\x13\n\x0b\x62ucket_name\x18\x01 \x01(\t\x12\x13\n\x0bobject_name\x18\x02 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x03 \x01(\t\">\n\x14UploadObjectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xbb\x01\n\x0cMinioService\x12R\n\x0bUploadFiles\x12 .minio_service.FileUploadRequest\x1a!.minio_service.FileUploadResponse\x12W\n\x0cUploadObject\x12\".minio_service.UploadObjectRequest\x1a#.minio_service.UploadObjectResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'minio_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEUPLOADREQUEST']._serialized_start=38
  _globals['_FILEUPLOADREQUEST']._serialized_end=118
  _globals['_FILEUPLOADRESPONSE']._serialized_start=120
  _globals['_FILEUPLOADRESPONSE']._serialized_end=174
  _globals['_UPLOADOBJECTREQUEST']._serialized_start=176
  _globals['_UPLOADOBJECTREQUEST']._serialized_end=261
  _globals['_UPLOADOBJECTRESPONSE']._serialized_start=263
  _globals['_UPLOADOBJECTRESPONSE']._serialized_end=325
  _globals['_MINIOSERVICE']._serialized_start=328
  _globals['_MINIOSERVICE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
