# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import minio_service_pb2 as minio__service__pb2


class MinioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFiles = channel.unary_unary(
                '/minio_service.MinioService/UploadFiles',
                request_serializer=minio__service__pb2.FileUploadRequest.SerializeToString,
                response_deserializer=minio__service__pb2.FileUploadResponse.FromString,
                )
        self.UploadObject = channel.unary_unary(
                '/minio_service.MinioService/UploadObject',
                request_serializer=minio__service__pb2.UploadObjectRequest.SerializeToString,
                response_deserializer=minio__service__pb2.UploadObjectResponse.FromString,
                )


class MinioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MinioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFiles,
                    request_deserializer=minio__service__pb2.FileUploadRequest.FromString,
                    response_serializer=minio__service__pb2.FileUploadResponse.SerializeToString,
            ),
            'UploadObject': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadObject,
                    request_deserializer=minio__service__pb2.UploadObjectRequest.FromString,
                    response_serializer=minio__service__pb2.UploadObjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minio_service.MinioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MinioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/minio_service.MinioService/UploadFiles',
            minio__service__pb2.FileUploadRequest.SerializeToString,
            minio__service__pb2.FileUploadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/minio_service.MinioService/UploadObject',
            minio__service__pb2.UploadObjectRequest.SerializeToString,
            minio__service__pb2.UploadObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
